theme: jekyll-theme-modernist


title: Roberto Tello
description: Respetuoso, Justo, Disciplinado, Comunicativo, Empático.

show_downloads: false
github:
  is_user_page: false
  repository_url: https://twitter.com/rtello151
  is_project_page: true
  github_name: robertotellomartin151
  
footballcloud:
  url: https://footballcloud.net
  editor: pedrogarcia
  
#  ![Octocat](https://pbs.twimg.com/profile_images/1034213562753994754/7M9-xAUG_400x400.jpg)
#![Branching](https://pbs.twimg.com/media/DkivQp-XcAAQJsq.jpg)